// Auth Dispatch States
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";
export const AUTHENTICATED_SUCCESS = "AUTHENTICATED_SUCCESS";
export const AUTHENTICATED_FAIL = "AUTHENTICATED_FAIL";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";

// Profile Dispatch States
export const LOAD_USER_PROFILE_SUCCESS = "LOAD_USER_PROFILE_SUCCESS";
export const LOAD_USER_PROFILE_FAIL = "LOAD_USER_PROFILE_FAIL";
export const UPDATE_USER_PROFILE_SUCCESS = "UPDATE_USER_PROFILE_SUCCESS";
export const UPDATE_USER_PROFILE_FAIL = "UPDATE_USER_PROFILE_FAIL";

// Flashcard Dispatch States
export const LOAD_FLASHCARDS_SUCCESS = "LOAD_FLASHCARDS_SUCCESS";
export const LOAD_FLASHCARDS_FAIL = "LOAD_FLASHCARDS_FAIL";
export const FLASHCARD_CREATION_SUCCESS = "FLASHCARD_CREATION_SUCCESS";
export const FLASHCARD_CREATION_FAIL = "FLASHCARD_CREATION_FAIL";
export const FLASHCARD_DELETION_SUCCESS = "FLASHCARD_DELETION_SUCCESS";
export const FLASHCARD_DELETION_FAIL = "FLASHCARD_DELETION_FAIL";
export const FLASHCARD_UPDATE_SUCCESS = "FLASHCARD_UPDATE_SUCCESS";
export const FLASHCARD_UPDATE_FAIL = "FLASHCARD_UPDATE_FAIL";

// Term Dispatch States
export const LOAD_TERMS_SUCCESS = "LOAD_TERMS_SUCCESS";
export const LOAD_TERMS_FAIL = "LOAD_TERMS_FAIL";
export const TERM_CREATION_SUCCESS = "TERM_CREATION_SUCCESS";
export const TERM_CREATION_FAIL = "TERM_CREATION_FAIL";
export const TERM_DELETION_SUCCESS = "TERM_DELETION_SUCCESS";
export const TERM_DELETION_FAIL = "TERM_DELETION_FAIL";
export const TERM_UPDATE_SUCCESS = "TERM_UPDATE_SUCCESS";
export const TERM_UPDATE_FAIL = "TERM_UPDATE_FAIL";
